"""Generate EDA_FINDINGS.md from the EDA artifacts — reproducible, not hand-typed.

    python EDA/make_findings.py

Reads ``artifacts/eda_facts.json`` (live stats) and ``artifacts/column_analysis.json``
(the adversarially-verified per-column handling decisions) and renders a single
Markdown write-up grouped by column family. Re-run it whenever either artifact
changes so the doc never drifts from the data.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import mappings  # noqa: E402

FACTS = json.loads((HERE / "artifacts" / "eda_facts.json").read_text())
ANALYSIS = json.loads((HERE / "artifacts" / "column_analysis.json").read_text())
OUT = HERE / "EDA_FINDINGS.md"

by_col = {c["column"]: c for c in ANALYSIS["columns"]}
comp = ANALYSIS.get("completeness", {})


def esc(s: str) -> str:
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


def main() -> None:
    L: list[str] = []
    sch, tgt, grp, dis = (FACTS["schema"], FACTS["target"],
                          FACTS["grouping"], FACTS["discharge_filter"])
    br = sch["base_rate"]

    L += [
        "# EDA Findings — Diabetes 30-Day Readmission",
        "",
        "> Auto-generated by `EDA/make_findings.py` from `artifacts/eda_facts.json` "
        "(live statistics) and `artifacts/column_analysis.json` (per-column handling "
        "decisions, independently analysed and adversarially verified against the "
        "graded rules). Do not hand-edit — re-run the generator.",
        "",
        "## 1. Dataset at a glance",
        "",
        f"- **{tgt['n_rows']:,}** encounters · **{grp['n_unique_patients']:,}** unique "
        f"patients · **{sch['n_columns_raw']-1}** feature columns (2 of which are keys).",
        f"- **Target** (`readmitted`, collapsed to binary `<30` → 1, else 0): positive "
        f"rate **{100*br:.2f}%**. Raw 3-class split: "
        + ", ".join(f"`{k}`={v:,}" for k, v in tgt["raw_distribution"].items()) + ".",
        f"- **Accuracy is a trap:** always-predict-\"no\" scores "
        f"**{100*tgt['majority_baseline_accuracy']:.1f}%** while catching zero at-risk "
        f"patients. Headline metrics: PR-AUC, recall@precision, calibration.",
        "",
        "### Two row-level traps",
        f"1. **Patient leakage (rule 2).** {grp['n_patients_multi_encounter']:,} patients "
        f"recur (up to {grp['max_encounters_per_patient']} encounters); "
        f"**{grp['pct_rows_from_repeat_patients']:.0f}%** of rows are repeat patients. "
        f"Split by `patient_nbr` with `GroupShuffleSplit`, never randomly.",
        f"2. **Impossible labels (rule 5).** **{dis['n_drop_rows']:,}** rows "
        f"({dis['pct_drop']:.1f}%) end in *expired* ({dis['n_expired_rows']:,}) or "
        f"*hospice* ({dis['n_hospice_rows']:,}) discharge and cannot be readmitted — "
        f"filter them, leaving **{dis['rows_after_filter']:,}** rows.",
        "",
    ]

    # drop list
    drops = [c["column"] for c in ANALYSIS["columns"] if c.get("drop_recommendation")]
    L += [
        "## 2. Columns recommended for dropping",
        "",
        f"{len(drops)} columns add no usable signal (zero / near-zero variance, or "
        "fabricated-if-imputed):",
        "",
        "> " + ", ".join(f"`{c}`" for c in drops),
        "",
        "Notably **`weight`** (96.9% missing, MNAR) is dropped as a value but retained "
        "as a `weight_recorded` 0/1 flag; **`examide`/`citoglipton`** are literal "
        "constants; the rest are medications prescribed to < 0.1% of encounters.",
        "",
    ]

    # missingness table
    miss = sorted(
        [(n, p["pct_missing"]) for n, p in FACTS["columns"].items() if p["pct_missing"] > 0],
        key=lambda x: -x[1],
    )
    L += [
        "## 3. Missingness & mechanism",
        "",
        "| Column | % missing | Mechanism | Fill strategy |",
        "|---|--:|---|---|",
    ]
    for name, pct in miss:
        rec = by_col.get(name, {})
        strat = esc(rec.get("recommended_strategy", ""))
        strat = strat[:160] + ("…" if len(strat) > 160 else "")
        L.append(f"| `{name}` | {pct:.1f} | {rec.get('missing_mechanism','—')} | {strat} |")
    L += [
        "",
        "*MNAR* = missing-not-at-random: the fact that a value is absent is itself "
        "informative (e.g. an A1c test was not *ordered*), so it is encoded as its own "
        "category or a 0/1 indicator — never imputed away.",
        "",
    ]

    # per-family detail
    L += ["## 4. Per-column handling decisions", ""]
    for family, cols in mappings.COLUMN_FAMILY.items():
        present = [c for c in cols if c in by_col]
        if not present:
            continue
        L += [f"### {family}", ""]
        for name in present:
            rec = by_col[name]
            f = FACTS["columns"].get(name, {})
            pct = f.get("pct_missing", rec.get("missing_pct", 0.0))
            lift = f.get("target_lift")
            head = f"#### `{name}`"
            tags = []
            if rec.get("drop_recommendation"):
                tags.append("**DROP**")
            tags.append(f"missing {pct:.1f}%")
            tags.append(f"{rec.get('missing_mechanism','—')}")
            if lift:
                tags.append(f"lift {lift:.2f}×")
            tags.append(f"conf {rec.get('confidence','—')}")
            L += [head, "", "· ".join(tags), ""]
            L += [f"- **Meaning.** {esc(rec.get('semantic_meaning',''))}"]
            L += [f"- **Distribution.** {esc(rec.get('value_interpretation',''))}"]
            L += [f"- **vs. target.** {esc(rec.get('target_relationship',''))}"]
            L += [f"- **Strategy.** {esc(rec.get('recommended_strategy',''))}"]
            L += [f"- **Why.** {esc(rec.get('imputation_rationale',''))}"]
            L += [f"- **Model transform.** {esc(rec.get('modeling_transform',''))}"]
            caveat = rec.get("leakage_or_caveat", "")
            if caveat and caveat.strip().lower() != "none":
                L += [f"- **⚠️ Caveat.** {esc(caveat)}"]
            rules = rec.get("graded_rule_refs") or []
            if rules:
                L += [f"- **Graded rules.** {', '.join(rules)}"]
            L += [""]

    # warnings + provenance
    warns = comp.get("dashboard_warnings", [])
    if warns:
        L += ["## 5. Reviewer warnings (consistency critic)", ""]
        L += [f"- {esc(w)}" for w in warns]
        L += [""]
    L += [
        "## 6. Provenance",
        "",
        f"- Generated from {len(ANALYSIS['columns'])} per-column analyses, each produced "
        "by an independent analyst agent and then refuted/corrected by an adversarial "
        f"verifier ({len(ANALYSIS.get('corrections', []))} corrections applied), with a "
        "final cross-family consistency critic.",
        "- All statistics trace to `artifacts/eda_facts.json`, computed live from "
        "`data/raw/diabetic_data.csv` with `na_values=\"?\"`.",
        "",
    ]

    OUT.write_text("\n".join(L))
    print(f"Wrote {OUT}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
